version: '3'
services:
  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: example
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example

